services:
  - type: web
    name: racm-generator-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: API_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: 3.13.0
